apiVersion: v1
kind: Pod
metadata:
  name: migrate-update-database-schema
spec:
  volumes:
  - name: gh-262-cloudsq1-proxy-terminate-sidecar
    emptyDir: {}
  containers:
  - name: app
    entrypoint: null
    command:
    - "/bin/sh"
    - "-c"
    - "trap 'touch /gh-262-cloudsq1-proxy-terminate-sidecar/done' EXIT\nflyway migrate"
    volumeMounts:
    - name: gh-262-cloudsq1-proxy-terminate-sidecar
      mountPath: /gh-262-cloudsq1-proxy-terminate-sidecar
    env:
    - name: DATABASE
      valueFrom:
        secretKeyRef:
          name: postgres-cjworkbench-credentials
          key: database
    - name: FLYWAY_URL
      value: "jdbc:postgresql://localhost/$(DATABASE)"
    - name: FLYWAY_USER
      valueFrom:
        secretKeyRef:
          name: postgres-cjworkbench-credentials
          key: username
    - name: FLYWAY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-cjworkbench-credentials
          key: password
  - name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.18.0-buster
    volumeMounts:
    - name: gh-262-cloudsq1-proxy-terminate-sidecar
      mountPath: /gh-262-cloudsq1-proxy-terminate-sidecar
    envFrom:
    - configMapRef:
        name: cjw-cloud-sql-config  # PROJECT_NAME, POSTGRES_REGION, POSTGRES_INSTANCE_ID
    command:
    - "/bin/sh"
    - "-c"
    - "/cloud_sql_proxy -ip_address_types=PRIVATE -log_debug_stdout=true -instances=$(PROJECT_NAME):$(POSTGRES_REGION):$(POSTGRES_INSTANCE_ID)=tcp:5432 & PROXY_PID=$!\n(until [ -f /gh-262-cloudsq1-proxy-terminate-sidecar/done ]; do sleep 1; done; kill $PROXY_PID) &\nwait $PROXY_PID\nPROXY_RETVAL=$?\nif [ -f /gh-262-cloudsq1-proxy-terminate-sidecar/done ]; then exit 0; fi; exit $PROXY_RETVAL"
    securityContext:
      runAsNonRoot: true
