- op: add
  path: /spec/template/spec/affinity
  value:
    nodeAffinity: # Move to preemptible nodes whenever one is available
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: eks.amazonaws.com/capacityType
            operator: In
            values: [ "SPOT" ]
