# All ingresses will share an ALB. Configure Host so they coexist nicely.
- op: add
  path: /spec/rules/0/host
  value: app.$(DOMAIN_NAME)

# Health checks
- op: add
  path: /metadata/annotations/alb.ingress.kubernetes.io~1healthcheck-path
  value: /healthz

# SSL
- op: add
  path: /metadata/annotations/alb.ingress.kubernetes.io~1certificate-arn
  value: $(APP_CERT_ARN)
