kind: Deployment
metadata:
  name: frontend-deployment
spec:
  template:
    spec:
      containers:
      - name: app
        resources:
          requests:
            cpu: 1400m
            memory: 2Gi
          limits:
            cpu: 1400m
            memory: 2Gi
