apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-expired-session-deleter-deployment
  labels:
    workbenchdata.com/preemptible: "true"
    workbenchdata.com/uses-database: "true"
    workbenchdata.com/uses-s3: "true"
spec:
  selector:
    matchLabels:
      app: cron-expired-session-deleter-app
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: cron-expired-session-deleter-app
    spec:
      serviceAccountName: cron-sa
      containers:
      - name: app
        image: "gcr.io/workbenchdata-ci/cron:REPLACEME"
        command: [ "bin/cron-expired-session-deleter" ]
        resources:
          requests:
            cpu: 0.1
            memory: 200Mi
          limits:
            cpu: 0.1
            memory: 200Mi
        envFrom: []
        env:
        - name: CJW_PRODUCTION
          value: 'True'
        - name: PYTHONUNBUFFERED
          value: '1'
        - name: _DOMAIN_NAME
          valueFrom:
            configMapKeyRef:
              name: workbench-config
              key: domainName
        - name: S3_BUCKET_NAME_PATTERN
          value: "%s.$(_DOMAIN_NAME)"
