apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher-deployment
  labels:
    workbenchdata.com/unsafe: "true"
    workbenchdata.com/preemptible: "true"
    workbenchdata.com/uses-database: "true"
    workbenchdata.com/uses-rabbitmq: "true"
    workbenchdata.com/uses-s3: "true"
spec:
  selector:
    matchLabels:
      app: fetcher-app
  template:
    metadata:
      labels:
        app: fetcher-app
    spec:
      serviceAccountName: fetcher-sa
      initContainers:
        # setup-sandboxes.sh needs special privileges; run it in an init container.
        #
        # We run this command separately because it runs with privileged: true.
        # (pyspawner shouldn't have permission to fiddle with the mount
        # namespace, lest malicious code use that permission to somehow escape
        # its sandbox.)
        #
        # See https://itnext.io/using-overlay-mounts-with-kubernetes-960375c05959
        - name: setup-sandboxes
          image: "gcr.io/workbenchdata-ci/fetcher:latest"
          securityContext:
            privileged: true  # so it can run mount and iptables
          command: [ "bash", "-x", "/app/cjwkernel/setup-sandboxes.sh", "all" ]
          volumeMounts:
            - mountPath: /var/lib/cjwkernel/chroot
              name: chroot
              mountPropagation: Bidirectional  # expose mounts to main app
      containers:
      - name: app
        image: "gcr.io/workbenchdata-ci/fetcher:latest"
        envFrom: []
        env:
        - name: CJW_PRODUCTION
          value: 'True'
        - name: PYTHONUNBUFFERED
          value: '1'
        - name: ASGI_THREADS
          value: '2'
        - name: _DOMAIN_NAME
          valueFrom:
            configMapKeyRef:
              name: workbench-config
              key: domainName
        - name: S3_BUCKET_NAME_PATTERN
          value: '%s.$(_DOMAIN_NAME)'
        volumeMounts:
        - mountPath: /var/lib/cjwkernel/chroot
          name: chroot
        securityContext:
          capabilities:
            add:
              - NET_ADMIN # To create network interface for sandbox in cjwkernel
      - name: teardown-sandboxes
        # "any volume mounts created by Containers in Pods must be destroyed
        # (unmounted) by the Containers on termination"
        # -- https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation
        image: "gcr.io/workbenchdata-ci/fetcher:latest"
        command: ["sh", "-c", "sleep infinity"]  # do nothing, until exit. (sh responds to INT signal)
        securityContext:
          privileged: true  # so it can unmount
        lifecycle:
          preStop:
            exec:
              command: ["bash", "-x", "/app/cjwkernel/teardown-sandboxes.sh"]
        volumeMounts:
        - mountPath: /var/lib/cjwkernel/chroot
          name: chroot
          mountPropagation: Bidirectional  # expose mounts to main app
      volumes:
      - name: chroot
        emptyDir: {}
