resources:
- cron-delta-deleter.yaml
- cron-deployment.yaml
- cron-expired-session-deleter.yaml
- cron-lesson-workflow-deleter.yaml
- fetcher-deployment.yaml
- frontend-deployment.yaml
- frontend-internal-tusd-hooks-service.yaml
- frontend-service.yaml
- intercom-sink-deployment.yaml
- renderer-deployment.yaml

configMapGenerator:
- name: workbench-config
  literals:
  - domainName=
- name: cjw-google-analytics
  literals:
  - CJW_GOOGLE_ANALYTICS=
- name: cjw-heap-analytics
  literals:
  - CJW_HEAP_ANALYTICS_ID=
- name: cjw-intercom
  literals:
  - CJW_INTERCOM_APP_ID=
