---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: frontend-frontend-config
spec:
  redirectToHttps:
    enabled: true
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: websockets-backend-config
spec:
  timeoutSec: 3600
  connectionDraining:
    drainingTimeoutSec: 30
