kind: Deployment
metadata:
  name: fetcher-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: app
        resources:
          # fetch() functions are usually network-constrained: CPU and RAM
          # usage are low.
          requests:
            cpu: 0.3
            memory: 1.2Gi
          limits:
            cpu: 0.3
            memory: 1.2Gi
