apiVersion: apps/v1
kind: Deployment
metadata:
  name: tusd-deployment
spec:
  template:
    spec:
      containers:
      - name: tusd
        env:
        - name: GCS_SERVICE_ACCOUNT_FILE
          value: /tusd-gcs-credentials/application_default_credentials.json
        volumeMounts:
        - mountPath: /tusd-gcs-credentials
          name: tusd-gcs-credentials
          readOnly: true
        args:
        - -port=8080
        - -behind-proxy
        - "-gcs-bucket=upload.$(DOMAIN_NAME)"
        - "-hooks-http=http://tusd-hooks-service/tusd-hooks"
        - -hooks-enabled-events=pre-finish
      volumes:
      - name: tusd-gcs-credentials
        secret:
          secretName: tusd-gcs-credentials
          items:
          - key: application_default_credentials.json
            path: application_default_credentials.json
