apiVersion: v1
kind: Pod
metadata:
  name: migrate-update-database-schema
spec:
  containers:
  - name: app
    env:
    - name: DATABASE
      valueFrom:
        secretKeyRef:
          name: postgres-cjworkbench-credentials
          key: database
    - name: DATABASE_HOST
      valueFrom:
        secretKeyRef:
          name: postgres-cjworkbench-credentials
          key: host
    - name: FLYWAY_URL
      value: "jdbc:postgresql://$(DATABASE_HOST)/$(DATABASE)"
    - name: FLYWAY_USER
      valueFrom:
        secretKeyRef:
          name: postgres-cjworkbench-credentials
          key: username
    - name: FLYWAY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-cjworkbench-credentials
          key: password
