apiVersion: apps/v1
kind: Deployment
metadata:
  name: many
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: CJW_INTERCOM_CLIENT_SECRETS
          value: secrets/intercom-oauth-secret/intercom-oauth-secret.json
        volumeMounts:
        - mountPath: /app/secrets/intercom-oauth-secret
          name: intercom-oauth-secret
          readOnly: true
      volumes:
      - name: intercom-oauth-secret
        secret:
          secretName: intercom-oauth-secret
          defaultMode: 0400
          items:
            - key: json
              path: intercom-oauth-secret.json
