apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: intercom-config.yaml
  target:
    name: frontend-deployment  # for auth
- path: intercom-config.yaml
  target:
    name: fetcher-deployment  # for module-fetch
